output "US_EAST_1_ML_DB_USERNAME" {
  value = var.US_EAST_1_ML_DB_USERNAME
}

output "US_EAST_1_ML_DB_PASSWORD" {
  value = var.US_EAST_1_ML_DB_PASSWORD
}

output "US_EAST_1_ANALYTICS_DB_USERNAME" {
  value = var.US_EAST_1_ANALYTICS_DB_USERNAME
}

output "US_EAST_1_ANALYTICS_DB_PASSWORD" {
  value = var.US_EAST_1_ANALYTICS_DB_PASSWORD
}

output "APPIUM_VIDEO_API_USERNAME" {
  value = var.APPIUM_VIDEO_API_USERNAME
}

output "APPIUM_VIDEO_API_PASSWORD" {
  value = var.APPIUM_VIDEO_API_PASSWORD
}

output "REAL_DEVICE_VIDEO_API_USERNAME" {
  value = var.REAL_DEVICE_VIDEO_API_USERNAME
}

output "REAL_DEVICE_VIDEO_API_PASSWORD" {
  value = var.REAL_DEVICE_VIDEO_API_PASSWORD
}

output "GEO_EDGE_USERNAME" {
  value = var.GEO_EDGE_USERNAME
}

output "GEO_EDGE_PASSWORD" {
  value = var.GEO_EDGE_PASSWORD
}

output "FLUIDSTACK_APP_ID" {
  value = var.FLUIDSTACK_APP_ID
}

output "FLUIDSTACK_SECRET" {
  value = var.FLUIDSTACK_SECRET
}

output "NEWRELIC_LICENSE_KEY" {
  value = var.NEWRELIC_LICENSE_KEY
}

output "US_EAST_1_MLTMA_LVMS_DB_NAME" {
  value = var.US_EAST_1_MLTMA_LVMS_DB_NAME
}

output "US_EAST_1_MLTMA_LTMS_DB_NAME" {
  value = var.US_EAST_1_MLTMA_LTMS_DB_NAME
}

output "US_EAST_1_MLTMA_LVMS_RDB_NAME" {
  value = var.US_EAST_1_MLTMA_LVMS_RDB_NAME
}

output "US_EAST_1_MLTMA_LTMS_RDB_NAME" {
  value = var.US_EAST_1_MLTMA_LTMS_RDB_NAME
}

output "US_EAST_1_MLTLS_DB_NAME" {
  value = var.US_EAST_1_MLTLS_DB_NAME
}

output "US_EAST_1_MLTLS_CF_ACCESS_KEY" {
  value = var.US_EAST_1_MLTLS_CF_ACCESS_KEY
}

output "US_EAST_1_MLTLS_CF_SECRET_KEY" {
  value = var.US_EAST_1_MLTLS_CF_SECRET_KEY
}

output "US_EAST_1_MLRMAA_AUTH_USERNAME" {
  value = var.US_EAST_1_MLRMAA_AUTH_USERNAME
}

output "US_EAST_1_MLRMAA_AUTH_TOKEN" {
  value = var.US_EAST_1_MLRMAA_AUTH_TOKEN
}

output "US_EAST_1_MLMTS_DB_NAME" {
  value = var.US_EAST_1_MLMTS_DB_NAME
}

output "US_EAST_1_MLMMS_DB_NAME" {
  value = var.US_EAST_1_MLMMS_DB_NAME
}

output "US_EAST_1_MLMDS_DB_NAME" {
  value = var.US_EAST_1_MLMDS_DB_NAME
}

output "US_EAST_1_MLMDS_AUTH_USERNAME" {
  value = var.US_EAST_1_MLMDS_AUTH_USERNAME
}

output "US_EAST_1_MLMDS_AUTH_TOKEN" {
  value = var.US_EAST_1_MLMDS_AUTH_TOKEN
}

output "US_EAST_1_MLMCC_DB_NAME" {
  value = var.US_EAST_1_MLMCC_DB_NAME
}

output "US_EAST_1_MHOSTAPI_DB_NAME" {
  value = var.US_EAST_1_MHOSTAPI_DB_NAME
}

output "US_EAST_1_MHOSTAPI_JWT_TOKEN" {
  value = var.US_EAST_1_MHOSTAPI_JWT_TOKEN
}

output "US_EAST_1_MHOSTAPI_VAULT_USERNAME" {
  value = var.US_EAST_1_MHOSTAPI_VAULT_USERNAME
}

output "US_EAST_1_MHOSTAPI_VAULT_PASSWORD" {
  value = var.US_EAST_1_MHOSTAPI_VAULT_PASSWORD
}

output "US_EAST_1_MLTMS_DB_NAME" {
  value = var.US_EAST_1_MLTMS_DB_NAME
}

output "US_EAST_1_MHOSTAPI_DB_USERNAME" {
  value = var.US_EAST_1_MHOSTAPI_DB_USERNAME
}

output "US_EAST_1_MHOSTAPI_DB_PASSWORD" {
  value = var.US_EAST_1_MHOSTAPI_DB_PASSWORD
}

output "US_EAST_1_MLTMA_LVMS_RDB_USERNAME" {
  value = var.US_EAST_1_MLTMA_LVMS_RDB_USERNAME
}

output "US_EAST_1_MLTMA_LVMS_RDB_PASSWORD" {
  value = var.US_EAST_1_MLTMA_LVMS_RDB_PASSWORD
}

output "US_EAST_1_MLTMA_LTMS_RDB_USERNAME" {
  value = var.US_EAST_1_MLTMA_LTMS_RDB_USERNAME
}

output "US_EAST_1_MLTMA_LTMS_RDB_PASSWORD" {
  value = var.US_EAST_1_MLTMA_LTMS_RDB_PASSWORD
}

output "US_EAST_1_MLTMA_LTMS_DB_PASSWORD" {
  value = var.US_EAST_1_MLTMA_LTMS_DB_PASSWORD
}

output "US_EAST_1_MLTMA_LTMS_DB_USERNAME" {
  value = var.US_EAST_1_MLTMA_LTMS_DB_USERNAME
}

output "US_EAST_1_MLTMA_LVMS_DB_PASSWORD" {
  value = var.US_EAST_1_MLTMA_LVMS_DB_PASSWORD
}

output "US_EAST_1_MLTMA_LVMS_DB_USERNAME" {
  value = var.US_EAST_1_MLTMA_LVMS_DB_USERNAME
}
