name: "Import github env secrets"
description: "Checks out the repository and does something"
inputs:
  product:  # id of input
    description: 'Name of the product'
    required: true
  env:
    description: 'Env name'
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2

  - name: Select environment variables
    shell: bash
    run: |
      echo 'TF_VAR_TEST=${{ secrets.TEST }}' >> $GITHUB_ENV
  
  - name: test
    shell: bash
    run: |
      echo "${{ github.event.inputs.product }}"
      echo "${{ github.event.inputs.env }}"
