name: Terraform

on:
  push:
    branches:
      - main
  pull_request:

jobs: 
  plan:
    name: Terragrunt Validate, Plan, Approval, Apply
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Checkout Codebase
        uses: actions/checkout@v3

      - run:  env

      - name: 'Terragrunt Init'
        id: init
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_TEST_1: ${{ secrets.TF_VAR_TEST_1 }}
          TF_VAR_TEST_2: ${{ secrets.TF_VAR_TEST_2 }}