name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to Perform'
        required: true
        type: choice
        options:
        - refresh
        - plan
        - apply
        - destroy
      product:
        description: 'Product Name to Deploy'
        required: true
        type: choice
        options:
        - common
        - auth
        - falcon
        - magicleap
        - hyperexecute
        - mobile
        - analytics
        - integrations
        - issue-tracker
        - tunnel
        - backend-internals
        - security-team

jobs: 
  plan:
    name: Terragrunt Validate, Plan, Approval, Apply
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: set environment
        run: |
          echo "TF_VAR_TEST_1=${{ secrets.TF_VAR_TEST_1 }}" >> $GITHUB_ENV
          echo "TF_VAR_TEST_2=${{ secrets.TF_VAR_TEST_2 }}" >> $GITHUB_ENV
    
      - name: 'Terragrunt init'
        id: init
        run: |
          terraform init

      - name: 'Terragrunt plan'
        id: plan
        run: |
          terraform plan -no-color

      - name: 'Terraform Approval'
        uses: macnev2013/manual-approval@v1.0.18
        with:
           secret: ${{ secrets.GITHUB_TOKEN }}
           approvers: monty16597
           approval-wait: 300
           minimum-approvals: 1
           issue-title: |
             Job: ${{ github.job }}
          #  issue-body: |
          #    #### Terraform Plan 📖 ${{ steps.plan.outcome }}

          #    <details>
          #     <summary>Show Plan</summary>

          #     ```terraform
          #     ${{ steps.plan.outputs.stdout }}
          #     ```
          #    </details>

      - name: 'Terragrunt apply'
        id: apply
        run: |
          terraform init
          terraform apply -auto-approve