name: 'Terraform'

on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  auto-approval-agent:
    runs-on: ubuntu-latest
    name: Auto approve PR
    steps:
      - name: Auto approve
        shell: sh
        run: |
          #!/bin/bash
          echo "test"
          OWNER_REPO="${{ github.repository }}"
          RUN_ID="${{ github.run_id }}"
          ENV_ID=`echo ${{ secrets.ENV_ID_MAPPING }} | jq '.${{ github.ref_name }}'`
          echo $ENV_ID
          echo "${{ github.run_id }}"
          echo "=="
          echo "${{ github.run_attempt }}"
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/$OWNER_REPO/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs
          # approved_flag=0
          # while [ $approved_flag  -eq 0 ]
          # do
          #     echo 'test'
          #     approved_flag=1
          #     # curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/$OWNER_REPO/actions/runs/2939708747/pending_deployments -d '{"environment_ids":[${{ secrets.ENV_ID_MAPPING }}],"state":"approved","comment":"Auto Approving :)"}'
          # done
        env:
          GH_TOKEN: "${{ secrets.ADMIN_GITHUB_TOKEN}}"

  terraform:
    name: Deployment on env ${{ needs.detect.outputs.env_name }}
    runs-on: ubuntu-latest
    environment: "${{ github.ref_name }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2