name: 'Terraform'

on:
  push:
    branches:
      - "main"
      - "master"
jobs:
  auto-approval-agent:
    runs-on: ubuntu-latest
    name: Auto approve PR
    env:
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      ENV_ID_MAPPING: '{
          "dev": "580684972"
        }'
    steps:
      - name: Auto approve
        shell: sh
        run: |
          #!/bin/bash
          echo "test"
          echo "{{ github.repository }}"
          echo "{{ github.run_id }}"
          # curl \
          #   -X POST \
          #   -H "Accept: application/vnd.github+json" \ 
          #   -H "Authorization: token <TOKEN>" \
          #   https://api.github.com/repos/{{ github.repository }}/actions/runs/{{ github.run_id }}/pending_deployments \
          #   -d '{"environment_ids":[161171787],"state":"approved","comment":"Ship it!"}'

  terraform:
    name: Deployment on env ${{ needs.detect.outputs.env_name }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2