name: Terraform

on:
  push:
    branches:
      - main
  pull_request:

jobs: 
  plan:
    name: Terragrunt Validate, Plan, Approval, Apply
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: unnecessary
          config: |
            Host *
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null
              ServerAliveInterval 60
              ServerAliveCountMax 30
          if_key_exists: fail 

      - name: shell
        run: |
          git clone git@github.com:LambdatestIncPrivate/sanrachna-module.git

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: set environment
        run: |
          echo "TF_VAR_TEST_1=${{ secrets.TF_VAR_TEST_1 }}" >> $GITHUB_ENV
          echo "TF_VAR_TEST_2=${{ secrets.TF_VAR_TEST_2 }}" >> $GITHUB_ENV

      - name: 'Terragrunt Init'
        id: init
        run: |
          terraform init
          terraform apply -auto-approve