name: Terraform

on:
  push:
    branches:
      - main


jobs: 
  plan:
    name: Plan on ${{ github.event.inputs.product }}
    runs-on: ubuntu-latest
    environment:
      name: prod_mobile
    steps:

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: set environment
        run: |
          echo "TF_VAR_US_EAST_1_ML_DB_USERNAME=${{ secrets.US_EAST_1_ML_DB_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_ML_DB_PASSWORD=${{ secrets.US_EAST_1_ML_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_ANALYTICS_DB_USERNAME=${{ secrets.US_EAST_1_ANALYTICS_DB_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_ANALYTICS_DB_PASSWORD=${{ secrets.US_EAST_1_ANALYTICS_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_APPIUM_VIDEO_API_USERNAME=${{ secrets.APPIUM_VIDEO_API_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_APPIUM_VIDEO_API_PASSWORD=${{ secrets.APPIUM_VIDEO_API_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_REAL_DEVICE_VIDEO_API_USERNAME=${{ secrets.REAL_DEVICE_VIDEO_API_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_REAL_DEVICE_VIDEO_API_PASSWORD=${{ secrets.REAL_DEVICE_VIDEO_API_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_GEO_EDGE_USERNAME=${{ secrets.GEO_EDGE_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_GEO_EDGE_PASSWORD=${{ secrets.GEO_EDGE_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_FLUIDSTACK_APP_ID=${{ secrets.FLUIDSTACK_APP_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_FLUIDSTACK_SECRET=${{ secrets.FLUIDSTACK_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_NEWRELIC_LICENSE_KEY=${{ secrets.NEWRELIC_LICENSE_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTMA_LVMS_DB_NAME=${{ secrets.US_EAST_1_MLTMA_LVMS_DB_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTMA_LTMS_DB_NAME=${{ secrets.US_EAST_1_MLTMA_LTMS_DB_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTMA_LVMS_RDB_NAME=${{ secrets.US_EAST_1_MLTMA_LVMS_RDB_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTMA_LTMS_RDB_NAME=${{ secrets.US_EAST_1_MLTMA_LTMS_RDB_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTLS_DB_NAME=${{ secrets.US_EAST_1_MLTLS_DB_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTLS_CF_ACCESS_KEY=${{ secrets.US_EAST_1_MLTLS_CF_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTLS_CF_SECRET_KEY=${{ secrets.US_EAST_1_MLTLS_CF_SECRET_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLRMAA_AUTH_USERNAME=${{ secrets.US_EAST_1_MLRMAA_AUTH_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLRMAA_AUTH_TOKEN=${{ secrets.US_EAST_1_MLRMAA_AUTH_TOKEN }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLMTS_DB_NAME=${{ secrets.US_EAST_1_MLMTS_DB_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLMMS_DB_NAME=${{ secrets.US_EAST_1_MLMMS_DB_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLMDS_DB_NAME=${{ secrets.US_EAST_1_MLMDS_DB_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLMDS_AUTH_USERNAME=${{ secrets.US_EAST_1_MLMDS_AUTH_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLMDS_AUTH_TOKEN=${{ secrets.US_EAST_1_MLMDS_AUTH_TOKEN }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLMCC_DB_NAME=${{ secrets.US_EAST_1_MLMCC_DB_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MHOSTAPI_DB_NAME=${{ secrets.US_EAST_1_MHOSTAPI_DB_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MHOSTAPI_JWT_TOKEN=${{ secrets.US_EAST_1_MHOSTAPI_JWT_TOKEN }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MHOSTAPI_VAULT_USERNAME=${{ secrets.US_EAST_1_MHOSTAPI_VAULT_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MHOSTAPI_VAULT_PASSWORD=${{ secrets.US_EAST_1_MHOSTAPI_VAULT_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTMS_DB_NAME=${{ secrets.US_EAST_1_MLTMS_DB_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MHOSTAPI_DB_USERNAME=${{ secrets.US_EAST_1_MHOSTAPI_DB_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MHOSTAPI_DB_PASSWORD=${{ secrets.US_EAST_1_MHOSTAPI_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTMA_LVMS_RDB_USERNAME=${{ secrets.US_EAST_1_MLTMA_LVMS_RDB_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTMA_LVMS_RDB_PASSWORD=${{ secrets.US_EAST_1_MLTMA_LVMS_RDB_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTMA_LTMS_RDB_USERNAME=${{ secrets.US_EAST_1_MLTMA_LTMS_RDB_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTMA_LTMS_RDB_PASSWORD=${{ secrets.US_EAST_1_MLTMA_LTMS_RDB_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTMA_LTMS_DB_PASSWORD=${{ secrets.US_EAST_1_MLTMA_LTMS_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTMA_LTMS_DB_USERNAME=${{ secrets.US_EAST_1_MLTMA_LTMS_DB_USERNAME }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTMA_LVMS_DB_PASSWORD=${{ secrets.US_EAST_1_MLTMA_LVMS_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_US_EAST_1_MLTMA_LVMS_DB_USERNAME=${{ secrets.US_EAST_1_MLTMA_LVMS_DB_USERNAME }}" >> $GITHUB_ENV

      - name: test
        run: |
          echo "TF_VAR_US_EAST_1_ML_DB_USERNAME=$TF_VAR_US_EAST_1_ML_DB_USERNAME" >> test.txt
          echo "TF_VAR_US_EAST_1_ML_DB_PASSWORD=$TF_VAR_US_EAST_1_ML_DB_PASSWORD" >> test.txt
          echo "TF_VAR_US_EAST_1_ANALYTICS_DB_USERNAME=$TF_VAR_US_EAST_1_ANALYTICS_DB_USERNAME" >> test.txt
          echo "TF_VAR_US_EAST_1_ANALYTICS_DB_PASSWORD=$TF_VAR_US_EAST_1_ANALYTICS_DB_PASSWORD" >> test.txt
          echo "TF_VAR_APPIUM_VIDEO_API_USERNAME=$TF_VAR_APPIUM_VIDEO_API_USERNAME" >> test.txt
          echo "TF_VAR_APPIUM_VIDEO_API_PASSWORD=$TF_VAR_APPIUM_VIDEO_API_PASSWORD" >> test.txt
          echo "TF_VAR_REAL_DEVICE_VIDEO_API_USERNAME=$TF_VAR_REAL_DEVICE_VIDEO_API_USERNAME" >> test.txt
          echo "TF_VAR_REAL_DEVICE_VIDEO_API_PASSWORD=$TF_VAR_REAL_DEVICE_VIDEO_API_PASSWORD" >> test.txt
          echo "TF_VAR_GEO_EDGE_USERNAME=$TF_VAR_GEO_EDGE_USERNAME" >> test.txt
          echo "TF_VAR_GEO_EDGE_PASSWORD=$TF_VAR_GEO_EDGE_PASSWORD" >> test.txt
          echo "TF_VAR_FLUIDSTACK_APP_ID=$TF_VAR_FLUIDSTACK_APP_ID" >> test.txt
          echo "TF_VAR_FLUIDSTACK_SECRET=$TF_VAR_FLUIDSTACK_SECRET" >> test.txt
          echo "TF_VAR_NEWRELIC_LICENSE_KEY=$TF_VAR_NEWRELIC_LICENSE_KEY" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTMA_LVMS_DB_NAME=$TF_VAR_US_EAST_1_MLTMA_LVMS_DB_NAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTMA_LTMS_DB_NAME=$TF_VAR_US_EAST_1_MLTMA_LTMS_DB_NAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTMA_LVMS_RDB_NAME=$TF_VAR_US_EAST_1_MLTMA_LVMS_RDB_NAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTMA_LTMS_RDB_NAME=$TF_VAR_US_EAST_1_MLTMA_LTMS_RDB_NAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTLS_DB_NAME=$TF_VAR_US_EAST_1_MLTLS_DB_NAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTLS_CF_ACCESS_KEY=$TF_VAR_US_EAST_1_MLTLS_CF_ACCESS_KEY" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTLS_CF_SECRET_KEY=$TF_VAR_US_EAST_1_MLTLS_CF_SECRET_KEY" >> test.txt
          echo "TF_VAR_US_EAST_1_MLRMAA_AUTH_USERNAME=$TF_VAR_US_EAST_1_MLRMAA_AUTH_USERNAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MLRMAA_AUTH_TOKEN=$TF_VAR_US_EAST_1_MLRMAA_AUTH_TOKEN" >> test.txt
          echo "TF_VAR_US_EAST_1_MLMTS_DB_NAME=$TF_VAR_US_EAST_1_MLMTS_DB_NAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MLMMS_DB_NAME=$TF_VAR_US_EAST_1_MLMMS_DB_NAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MLMDS_DB_NAME=$TF_VAR_US_EAST_1_MLMDS_DB_NAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MLMDS_AUTH_USERNAME=$TF_VAR_US_EAST_1_MLMDS_AUTH_USERNAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MLMDS_AUTH_TOKEN=$TF_VAR_US_EAST_1_MLMDS_AUTH_TOKEN" >> test.txt
          echo "TF_VAR_US_EAST_1_MLMCC_DB_NAME=$TF_VAR_US_EAST_1_MLMCC_DB_NAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MHOSTAPI_DB_NAME=$TF_VAR_US_EAST_1_MHOSTAPI_DB_NAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MHOSTAPI_JWT_TOKEN=$TF_VAR_US_EAST_1_MHOSTAPI_JWT_TOKEN" >> test.txt
          echo "TF_VAR_US_EAST_1_MHOSTAPI_VAULT_USERNAME=$TF_VAR_US_EAST_1_MHOSTAPI_VAULT_USERNAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MHOSTAPI_VAULT_PASSWORD=$TF_VAR_US_EAST_1_MHOSTAPI_VAULT_PASSWORD" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTMS_DB_NAME=$TF_VAR_US_EAST_1_MLTMS_DB_NAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MHOSTAPI_DB_USERNAME=$TF_VAR_US_EAST_1_MHOSTAPI_DB_USERNAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MHOSTAPI_DB_PASSWORD=$TF_VAR_US_EAST_1_MHOSTAPI_DB_PASSWORD" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTMA_LVMS_RDB_USERNAME=$TF_VAR_US_EAST_1_MLTMA_LVMS_RDB_USERNAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTMA_LVMS_RDB_PASSWORD=$TF_VAR_US_EAST_1_MLTMA_LVMS_RDB_PASSWORD" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTMA_LTMS_RDB_USERNAME=$TF_VAR_US_EAST_1_MLTMA_LTMS_RDB_USERNAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTMA_LTMS_RDB_PASSWORD=$TF_VAR_US_EAST_1_MLTMA_LTMS_RDB_PASSWORD" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTMA_LTMS_DB_PASSWORD=$TF_VAR_US_EAST_1_MLTMA_LTMS_DB_PASSWORD" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTMA_LTMS_DB_USERNAME=$TF_VAR_US_EAST_1_MLTMA_LTMS_DB_USERNAME" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTMA_LVMS_DB_PASSWORD=$TF_VAR_US_EAST_1_MLTMA_LVMS_DB_PASSWORD" >> test.txt
          echo "TF_VAR_US_EAST_1_MLTMA_LVMS_DB_USERNAME=$TF_VAR_US_EAST_1_MLTMA_LVMS_DB_USERNAME" >> test.txt

          cat test.txt


      - name: 'Terragrunt init'
        id: init
        run: |
          terraform init

      - name: 'Terragrunt plan'
        id: plan
        run: |
          terraform plan -no-color

      - name: 'Terragrunt apply'
        id: apply
        run: |
          terraform apply -auto-approve