name: Single Env Terraform
run-name: ${{ github.event.inputs.tf_operation }} On ${{ github.event.inputs.environment_name }}
on:
  workflow_call:
    inputs:
      environment_name:
        description: "Environment Name"
        required: true
        type: string
        default: dev
      tf_operation:
        description: "Terraform Operation"
        required: true
        type: string
        default: plan

  workflow_dispatch:
    inputs:
      environment_name:
        description: "Environment Name"
        required: true
        type: choice
        default: dev
        options:
          - dev
          - staging
          - prod

      tf_operation:
        description: "Terraform Operation"
        required: true
        type: choice
        default: plan
        options:
          - plan
          - apply

jobs:
  main:
    runs-on: ubuntu-latest # GFL Runner tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Init
        run: terraform init
      
      - name: test
        run: echo "${{ github.event_name }}"

      - name: Plan
        id: plan
        run: terraform plan -out=tfplan
      
      - name: generate tfplan summary
        id: plan-summarize
        if: always() && github.event_name == 'pull_request'
        run: |
          if [ '${{ steps.plan.outcome }}' == 'success' ]; then
            echo '# Terraform Plan Summary' > tfplan-summary.md
            terraform show -json tfplan > tfplan.json
            tf-summarize -md tfplan.json >> tfplan-summary.md
          fi
          if [ '${{ steps.plan.outcome }}' == 'failure' ]; then
            echo '# Terraform Plan Error' >> tfplan-summary.md
            echo '```terraform' >> tfplan-summary.md
            (echo '${{ steps.plan.outputs.stderr }}' | sed -r "s/[[:cntrl:]]\[[0-9]{1,3}m//g") >> tfplan-summary.md
            echo '```' >> tfplan-summary.md
          fi

      - name: Notify
        uses: thollander/actions-comment-pull-request@v3
        if: always() && github.event_name == 'pull_request'
        with:
          comment-tag: "plan-summarize"
          create-if-not-exists: true
          mode: "recreate"
          file-path: "tfplan-summary.md"

      - name: Run
        if: github.event_name == 'workflow_dispatch' && inputs.tf_operation == 'apply'
        run: terraform apply -auto-approve tfplan